In [1]:
import numpy as np
import utils
from utils import *
import itertools
import random

In [31]:
folder_name = "../Toroidal_topology_grid_cell_data/"

In [2]:
a = np.load("../Toroidal_topology_grid_cell_data/rat_r_day1_grid_modules_1_2_3.npz",allow_pickle=True)

In [3]:
a.files

['spikes_mod1', 'spikes_mod2', 'spikes_mod3', 'x', 'y', 't', 'z', 'azimuth']

In [4]:
a['x']

array([-0.47897512, -0.47518063, -0.47168648, ...,  0.4646765 ,
        0.4671132 ,  0.46969566], dtype=float32)

In [5]:
d = dict(zip((str(k) for k in a), (a[k] for k in a)))

In [6]:
d.keys()

dict_keys(['spikes_mod1', 'spikes_mod2', 'spikes_mod3', 'x', 'y', 't', 'z', 'azimuth'])

In [7]:
d['spikes_mod1'].item()

{0: array([ 7457.5409    ,  7458.01693333,  7458.14456667, ...,
        21626.1872    , 21631.8351    , 21633.5363    ]),
 1: array([ 7459.24686667,  7459.9919    ,  7460.00466667, ...,
        21597.61323333, 21619.25986667, 21622.67153333]),
 2: array([ 7458.6629    ,  7463.00626667,  7470.1531    , ...,
        21631.17483333, 21631.29813333, 21631.82373333]),
 3: array([ 7457.1354    ,  7457.36046667,  7458.14426667, ...,
        21631.40226667, 21637.00676667, 21637.24873333]),
 4: array([ 7461.43973333,  7464.32866667,  7465.59683333, ...,
        21616.4406    , 21627.55033333, 21633.09443333]),
 5: array([ 7464.82396667,  7465.07326667,  7465.60643333, ...,
        21606.93136667, 21608.37666667, 21610.4704    ]),
 6: array([ 7457.04083333,  7457.9092    ,  7458.25123333, ...,
        21639.48246667, 21639.73516667, 21639.74136667]),
 7: array([ 7457.9004    ,  7458.02946667,  7460.72886667, ...,
        21638.57173333, 21639.35616667, 21639.61983333]),
 8: array([ 7457.906    

In [8]:
d['spikes_mod1'].item().keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165])

In [9]:
d['spikes_mod2'].item().keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167])

In [10]:
d['spikes_mod3'].item().keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148])

In [11]:
len(d['spikes_mod1'].item()[3])

35101

In [12]:
total = 0
for key, val in d['spikes_mod1'].item().items():
    total += len(val)
for key, val in d['spikes_mod2'].item().items():
    total += len(val)
for key, val in d['spikes_mod3'].item().items():
    total += len(val)

print(total)
#d['spikes_mod2'].item()

16849310


In [13]:
len(d['x'])

1418299

In [14]:
d['x']

array([-0.47897512, -0.47518063, -0.47168648, ...,  0.4646765 ,
        0.4671132 ,  0.46969566], dtype=float32)

In [15]:
d['y']

array([-0.54703695, -0.5431891 , -0.53941685, ..., -0.72706604,
       -0.72636205, -0.7252686 ], dtype=float32)

In [16]:
d['t']

array([ 7457.01,  7457.02,  7457.03, ..., 21639.97, 21639.98, 21639.99])

In [17]:
d['t']

array([ 7457.01,  7457.02,  7457.03, ..., 21639.97, 21639.98, 21639.99])

In [18]:
len(d['z'])

1418299

In [19]:
len(d['azimuth'])

1418299

In [20]:
rat_name = 'R'
mod_name = '2'
sess_name = 'OF'
day_name = 'day1'

In [21]:
#spikes_bin, xx, yy, aa, tt = get_spikes(rat_name, mod_name, day_name, sess_name, bSmooth = True, bSpeed = True, folder = "Toroidal_topology_grid_cell_data/")

In [22]:
#spikes_bin.shape

In [23]:
#spikes_bin[0]

In [24]:
#xx.shape

In [25]:
#yy.shape

In [26]:
#aa.shape

In [27]:
#tt.shape

In [32]:
load_pos("r", "OF", day_name = 'day1', bSpeed = False, folder = folder_name)

(array([-0.47897512, -0.47707787, -0.47518063, ...,  0.68280774,
         0.6830079 ,  0.68310376]),
 array([-0.54703695, -0.54511303, -0.54318911, ..., -0.35497057,
        -0.35531771, -0.35541726]),
 array([0.22731559, 0.22831983, 0.22932407, ..., 0.72156394, 0.72580314,
        0.72696052]),
 array([ 7457.  ,  7457.01,  7457.02, ..., 16044.97, 16044.98, 16044.99]))

In [35]:
tens = [10,20,30,40,50,60,70,80,90,100,110,120,130,140]
alpha_all = np.zeros((len(tens), 100))

rat_name = 'R'
mod_name = '2'
sess_name = 'OF'
day_name = 'day1'

nums = 3
angs = np.zeros((len(tens), nums))
xlen = np.zeros((len(tens), nums))
ylen = np.zeros((len(tens), nums))
score1 = np.zeros((len(tens), nums))
score2 = np.zeros((len(tens), nums))
nn = -1
dim = 6
ph_classes = [0,1] # Decode the ith most persistent cohomology class
num_circ = len(ph_classes)
dec_tresh = 0.99
metric = 'cosine'
maxdim = 1
coeff = 47
active_times = 15000
k = 1000
num_times = 5
n_points = 1200
nbs = 800

sspikes_all, xx,yy = get_spikes(rat_name, mod_name, day_name, sess_name, bType = 'pure',
                                 bSmooth = True, bSpeed = True, folder = folder_name)[:3]
spikes_all = get_spikes(rat_name, mod_name, day_name, sess_name, bType = 'pure', bSmooth = False, bSpeed = True, folder = folder_name)[0]


In [ ]:

num_neurons_all = len(spikes_all[0,:])
for nn, n  in enumerate(tens):   
    combinations_sample = list(itertools.islice(random_combinations(np.arange(num_neurons_all), n), nums))
    for j, comb  in enumerate(combinations_sample):        
        sspikes = sspikes_all[:, comb].copy()
        spikes = spikes_all[:, comb].copy()
        num_neurons = len(sspikes[0,:])            
        times_cube = np.arange(0,len(sspikes[:,0]),num_times)
        movetimes = np.sort(np.argsort(np.sum(sspikes[times_cube,:],1))[-active_times:])
        movetimes = times_cube[movetimes]

        dim_red_spikes_move_scaled,__,__ = pca(preprocessing.scale(sspikes[movetimes,:]), dim = dim)
        indstemp,dd,fs  = sample_denoising(dim_red_spikes_move_scaled,  k, 
                                            n_points, 1, metric)
        dim_red_spikes_move_scaled = dim_red_spikes_move_scaled[indstemp,:]
        X = squareform(pdist(dim_red_spikes_move_scaled, metric))
        knn_indices = np.argsort(X)[:, :nbs]
        knn_dists = X[np.arange(X.shape[0])[:, None], knn_indices].copy()
        sigmas, rhos = smooth_knn_dist(knn_dists, nbs, local_connectivity=0)
        rows, cols, vals = compute_membership_strengths(knn_indices, knn_dists, sigmas, rhos)
        result = coo_matrix((vals, (rows, cols)), shape=(X.shape[0], X.shape[0]))
        result.eliminate_zeros()
        transpose = result.transpose()
        prod_matrix = result.multiply(transpose)
        result = (result + transpose - prod_matrix)
        result.eliminate_zeros()
        d = result.toarray()
        d = -np.log(d)
        np.fill_diagonal(d,0)

        persistence = ripser(d, maxdim=maxdim, coeff=coeff, do_cocycles= True, distance_matrix = True)    

        diagrams = persistence["dgms"] # the multiset describing the lives of the persistence classes
        cocycles = persistence["cocycles"][1] # the cocycle representatives for the 1-dim classes
        dists_land = persistence["dperm2all"] # the pairwise distance between the points 
        births1 = diagrams[1][:, 0] #the time of birth for the 1-dim classes
        deaths1 = diagrams[1][:, 1] #the time of death for the 1-dim classes
        deaths1[np.isinf(deaths1)] = 0
        lives1 = deaths1-births1 # the lifetime for the 1-dim classes
        iMax = np.argsort(lives1)
        coords1 = np.zeros((num_circ, len(indstemp)))
        threshold = births1[iMax[-2]] + (deaths1[iMax[-2]] - births1[iMax[-2]])*dec_tresh
        for c in ph_classes:
            cocycle = cocycles[iMax[-(c+1)]]
            coords1[c,:],inds = get_coords(cocycle, threshold, len(indstemp), dists_land, coeff)

        num_neurons = len(sspikes[0,:])
        centcosall = np.zeros((num_neurons, 2, n_points))
        centsinall = np.zeros((num_neurons, 2, n_points))
        dspk = preprocessing.scale(sspikes[movetimes[indstemp],:])

        for neurid in range(num_neurons):
            spktemp = dspk[:, neurid].copy()
            centcosall[neurid,:,:] = np.multiply(np.cos(coords1[:, :]*2*np.pi),spktemp)
            centsinall[neurid,:,:] = np.multiply(np.sin(coords1[:, :]*2*np.pi),spktemp)
        times = np.where(np.sum(spikes>0, 1)>=1)[0]
        dspk = preprocessing.scale(sspikes)
        sspikes = sspikes[times,:]
        dspk = dspk[times,:]

        a = np.zeros((len(sspikes[:,0]), 2, num_neurons))
        for n in range(num_neurons):
            a[:,:,n] = np.multiply(dspk[:,n:n+1],np.sum(centcosall[n,:,:],1))

        c = np.zeros((len(sspikes[:,0]), 2, num_neurons))
        for n in range(num_neurons):
            c[:,:,n] = np.multiply(dspk[:,n:n+1],np.sum(centsinall[n,:,:],1))

        mtot2 = np.sum(c,2)
        mtot1 = np.sum(a,2)
        coords = np.arctan2(mtot2,mtot1)%(2*np.pi)

        m1b_1, m2b_1, xedge,yedge = get_ang_hist(coords[:,0], 
            coords[:,1], xx[times],yy[times])
        p1b_1, f1 = fit_sine_wave(m1b_1)
        p2b_1, f2 = fit_sine_wave(m2b_1)

        x,y = rot_para(p1b_1,p2b_1)
        xmin = xedge.min()
        xedge -= xmin
        xmax = xedge.max()
        ymin = yedge.min()
        yedge -= ymin
        ymax = yedge.max()

        angs[nn,j] = ((y[0]-x[0])/(2*np.pi)*360)%360
        xlen[nn,j] = 1/x[2]*xmax
        ylen[nn,j] = 1/y[2]*ymax
        score1[nn,j] = f1
        score2[nn,j] = f2
        print(angs[nn,j])
np.savez(folder_name + '/Results/toroidal_classification', 
         angs=angs, xlen=xlen, ylen=ylen, score1=score1, score2=score2)



OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


60.84193096777371


/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


71.19506955243617


/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


119.45262731783677


/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


51.682569865783535


/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


0.3622755650282146


/var/folders/tr/3zw9td7531z0_hhwc8105rv00000gn/T/ipykernel_27535/3581328054.py:28: RuntimeWarning: divide by zero encountered in log
  d = -np.log(d)


1.5820330612675735


In [ ]:
tens = [10, 20, 30, 40, 50, 60, 70, 80, 90,100,110,120,130,140]

f = np.load(folder_name + '/Results/toroidal_classification.npz', allow_pickle = True)
angs = f['angs']
xlen = f['xlen']
ylen = f['ylen']
score1 = f['score1']
score2 = f['score2']
f.close()

plt.figure()
ax = plt.axes()
successes = np.zeros(len(tens))
fit_thresh = 0.25
for i in range(len(tens)):
    successes[i] = np.sum(((angs[i,:]<70) & 
                           (angs[i,:]>50) &
                           (np.abs(1-xlen[i,:]/ylen[i,:])<0.25) &
                           (score1[i,:]<fit_thresh) & 
                           (score2[i,:]<fit_thresh)))
    
ax.plot(np.concatenate(([0], np.divide(tens,140)))*100,
        np.concatenate(([0], successes/nums*100)), label='0.25', lw = 5)
ax.set_xticks(np.divide([0,35,70,105,140],140)*100)
ax.set_xticklabels(('','','','',''))
ax.set_yticks((0,25,50,75,100))
ax.set_yticklabels(('','','','',''))
ax.set_aspect('equal', 'box')